/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BarChartDemo.java
 *
 * Created on 7-feb-2012, 15.28.46
 */

package ClientCRC;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GradientPaint;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author alessandro
 */
public class BarChartDemo extends javax.swing.JFrame {
private Font myFont = new Font("Tahoma", Font.PLAIN,11);
    /** Creates new form BarChartDemo */
    public BarChartDemo(int nessuno, int prima, int seconda, int terza, int quarta,
                        int nessuno40, int prima40, int seconda40, int terza40, int quarta40,
                        int nessuno60, int prima60, int seconda60, int terza60, int quarta60,
                        int nessuno80, int prima80, int seconda80, int terza80, int quarta80,
                        int nessunomagg, int primamagg, int secondamagg, int terzamagg, int quartamagg) {
        initComponents();

        jnessuno.setDisplayedMnemonic(nessuno);
        jprima.setDisplayedMnemonic(prima);
        jseconda.setDisplayedMnemonic(seconda);
        jterza.setDisplayedMnemonic(terza);
        jquarta.setDisplayedMnemonic(quarta);
        jnessuno1.setDisplayedMnemonic(nessuno40);
        jprima1.setDisplayedMnemonic(prima40);
        jseconda1.setDisplayedMnemonic(seconda40);
        jterza1.setDisplayedMnemonic(terza40);
        jquarta1.setDisplayedMnemonic(quarta40);
        jnessuno2.setDisplayedMnemonic(nessuno60);
        jprima2.setDisplayedMnemonic(prima60);
        jseconda2.setDisplayedMnemonic(seconda60);
        jterza2.setDisplayedMnemonic(terza60);
        jquarta2.setDisplayedMnemonic(quarta60);
        jnessuno3.setDisplayedMnemonic(nessuno80);
        jprima3.setDisplayedMnemonic(prima80);
        jseconda3.setDisplayedMnemonic(seconda80);
        jterza3.setDisplayedMnemonic(terza80);
        jquarta3.setDisplayedMnemonic(quarta80);
        jnessuno4.setDisplayedMnemonic(nessunomagg);
        jprima4.setDisplayedMnemonic(primamagg);
        jseconda4.setDisplayedMnemonic(secondamagg);
        jterza4.setDisplayedMnemonic(terzamagg);
        jquarta4.setDisplayedMnemonic(quartamagg);

        final CategoryDataset dataset = createDataset();
        
        final JFreeChart chart = createChart(dataset);
        
        final ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(1500, 870));
        chartPanel.setFont(myFont);
        
        setContentPane(chartPanel);
        this.setSize(700, 450);
        this.setLocation(0,320);
        this.setFont(myFont);
        this.setForeground(Color.yellow);
        this.setBackground(Color.darkGray);
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jprima = new javax.swing.JLabel();
        jseconda = new javax.swing.JLabel();
        jterza = new javax.swing.JLabel();
        jnessuno = new javax.swing.JLabel();
        jquarta = new javax.swing.JLabel();
        jseconda1 = new javax.swing.JLabel();
        jprima1 = new javax.swing.JLabel();
        jquarta1 = new javax.swing.JLabel();
        jnessuno1 = new javax.swing.JLabel();
        jterza1 = new javax.swing.JLabel();
        jnessuno2 = new javax.swing.JLabel();
        jseconda2 = new javax.swing.JLabel();
        jquarta2 = new javax.swing.JLabel();
        jprima2 = new javax.swing.JLabel();
        jterza2 = new javax.swing.JLabel();
        jprima3 = new javax.swing.JLabel();
        jterza3 = new javax.swing.JLabel();
        jseconda3 = new javax.swing.JLabel();
        jquarta3 = new javax.swing.JLabel();
        jnessuno3 = new javax.swing.JLabel();
        jterza4 = new javax.swing.JLabel();
        jprima4 = new javax.swing.JLabel();
        jnessuno4 = new javax.swing.JLabel();
        jquarta4 = new javax.swing.JLabel();
        jseconda4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jprima.setText("jLabel1");

        jseconda.setText("jLabel1");

        jterza.setText("jLabel1");

        jnessuno.setText("jLabel1");

        jquarta.setText("jLabel1");

        jseconda1.setText("jLabel1");

        jprima1.setText("jLabel1");

        jquarta1.setText("jLabel1");

        jnessuno1.setText("jLabel1");

        jterza1.setText("jLabel1");

        jnessuno2.setText("jLabel1");

        jseconda2.setText("jLabel1");

        jquarta2.setText("jLabel1");

        jprima2.setText("jLabel1");

        jterza2.setText("jLabel1");

        jprima3.setText("jLabel1");

        jterza3.setText("jLabel1");

        jseconda3.setText("jLabel1");

        jquarta3.setText("jLabel1");

        jnessuno3.setText("jLabel1");

        jterza4.setText("jLabel1");

        jprima4.setText("jLabel1");

        jnessuno4.setText("jLabel1");

        jquarta4.setText("jLabel1");

        jseconda4.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jprima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jterza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jquarta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jseconda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnessuno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jprima1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jterza1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jquarta1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jseconda1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnessuno1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jprima2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jterza2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jquarta2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jseconda2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnessuno2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jprima3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jterza3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jquarta3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jseconda3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnessuno3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jprima4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jterza4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jquarta4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jseconda4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnessuno4)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jprima)
                    .addComponent(jterza)
                    .addComponent(jquarta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jseconda)
                    .addComponent(jnessuno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jprima1)
                    .addComponent(jterza1)
                    .addComponent(jquarta1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jseconda1)
                    .addComponent(jnessuno1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jprima2)
                    .addComponent(jterza2)
                    .addComponent(jquarta2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jseconda2)
                    .addComponent(jnessuno2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jprima3)
                    .addComponent(jterza3)
                    .addComponent(jquarta3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jseconda3)
                    .addComponent(jnessuno3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jprima4)
                    .addComponent(jterza4)
                    .addComponent(jquarta4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jseconda4)
                    .addComponent(jnessuno4))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    private CategoryDataset createDataset() {

        // row keys...
        //final String series1 = "giorni di ricovero nella soglia";
        final String series2 = "0-10 giorni in più";
        final String series3 = "10-20 giorni in più";
        final String series4 = "20-30 giorni in più";
        final String series5 = "> 30 giorni in più";

        // column keys...
        final String category1 = "0-20 anni";
        final String category2 = "20-40 anni";
        final String category3 = "40-60 anni";
        final String category4 = "60-80 anni";
        final String category5 = "> 80 anni";

        // create the dataset...
        final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        int nessuno = jnessuno.getDisplayedMnemonic();
        int prima = jprima.getDisplayedMnemonic();
        int seconda = jseconda.getDisplayedMnemonic();
        int terza = jterza.getDisplayedMnemonic();
        int quarta = jquarta.getDisplayedMnemonic();
        int nessuno40 = jnessuno1.getDisplayedMnemonic();
        int prima40 = jprima1.getDisplayedMnemonic();
        int seconda40 = jseconda1.getDisplayedMnemonic();
        int terza40 = jterza1.getDisplayedMnemonic();
        int quarta40 = jquarta1.getDisplayedMnemonic();
        int nessuno60 = jnessuno2.getDisplayedMnemonic();
        int prima60 = jprima2.getDisplayedMnemonic();
        int seconda60 = jseconda2.getDisplayedMnemonic();
        int terza60 = jterza2.getDisplayedMnemonic();
        int quarta60 = jquarta2.getDisplayedMnemonic();
        int nessuno80 = jnessuno3.getDisplayedMnemonic();
        int prima80 = jprima3.getDisplayedMnemonic();
        int seconda80 = jseconda3.getDisplayedMnemonic();
        int terza80 = jterza3.getDisplayedMnemonic();
        int quarta80 = jquarta3.getDisplayedMnemonic();
        int nessunomagg = jnessuno4.getDisplayedMnemonic();
        int primamagg = jprima4.getDisplayedMnemonic();
        int secondamagg = jseconda4.getDisplayedMnemonic();
        int terzamagg = jterza4.getDisplayedMnemonic();
        int quartamagg = jquarta4.getDisplayedMnemonic();


        //dataset.addValue(nessuno, series1, category1);
        //dataset.addValue(nessuno40, series1, category2);
        //dataset.addValue(nessuno60, series1, category3);
        //dataset.addValue(nessuno80, series1, category4);
        //dataset.addValue(nessunomagg, series1, category5);
        
        
        
        dataset.addValue(prima, series2, category1);
        dataset.addValue(prima40, series2, category2);
        dataset.addValue(prima60, series2, category3);
        dataset.addValue(prima80, series2, category4);
        dataset.addValue(primamagg, series2, category5);

        dataset.addValue(seconda, series3, category1);
        dataset.addValue(seconda40, series3, category2);
        dataset.addValue(seconda60, series3, category3);
        dataset.addValue(seconda80, series3, category4);
        dataset.addValue(secondamagg, series3, category5);

        dataset.addValue(terza, series4, category1);
        dataset.addValue(terza40, series4, category2);
        dataset.addValue(terza60, series4, category3);
        dataset.addValue(terza80, series4, category4);
        dataset.addValue(terzamagg, series4, category5);

        dataset.addValue(quarta, series5, category1);
        dataset.addValue(quarta40, series5, category2);
        dataset.addValue(quarta60, series5, category3);
        dataset.addValue(quarta80, series5, category4);
        dataset.addValue(quartamagg, series5, category5);

        return dataset;

    }

    /**
     * Creates a sample chart.
     *
     * @param dataset  the dataset.
     *
     * @return The chart.
     */
    private JFreeChart createChart(final CategoryDataset dataset) {

        // create the chart...
        final JFreeChart chart = ChartFactory.createBarChart(
            "Ricoveri con giorni di degenza superiori al valore soglia",         // chart title
            "Età dei pazienti",               // domain axis label
            "N.ro di ricoveri",                  // range axis label
            dataset,                  // data
            PlotOrientation.VERTICAL, // orientation
            true,                     // include legend
            true,                     // tooltips?
            false                     // URLs?
        );

        // NOW DO SOME OPTIONAL CUSTOMISATION OF THE CHART...

        // set the background color for the chart...
        chart.setBackgroundPaint(Color.gray);
        
        // get a reference to the plot for further customisation...
        final CategoryPlot plot = chart.getCategoryPlot();
        
        plot.setBackgroundPaint(Color.white);
        plot.setDomainGridlinePaint(Color.black);
        plot.setRangeGridlinePaint(Color.black);
        
        // set the range axis to display integers only...
        final NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());

        // disable bar outlines...
        final BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setDrawBarOutline(false);

        // set up gradient paints for series...
        final GradientPaint gp0 = new GradientPaint(
            0.0f, 0.0f, Color.green,
            0.0f, 0.0f, Color.black
        );
        final GradientPaint gp1 = new GradientPaint(
            0.0f, 0.0f, Color.yellow,
            0.0f, 0.0f, Color.black
        );
        final GradientPaint gp2 = new GradientPaint(
            0.0f, 0.0f, Color.cyan,
            0.0f, 0.0f, Color.black
        );
        final GradientPaint gp3 = new GradientPaint(
            0.0f, 0.0f, Color.magenta,
            0.0f, 0.0f, Color.black
        );
        final GradientPaint gp4 = new GradientPaint(
            0.0f, 0.0f, Color.red,
            0.0f, 0.0f, Color.black
        );
        renderer.setSeriesPaint(0, gp0);
        renderer.setSeriesPaint(1, gp1);
        renderer.setSeriesPaint(2, gp2);
        renderer.setSeriesPaint(3, gp3);
        renderer.setSeriesPaint(4, gp4);

        final CategoryAxis domainAxis = plot.getDomainAxis();
        domainAxis.setCategoryLabelPositions(
            CategoryLabelPositions.createUpRotationLabelPositions(Math.PI / 6.0)
        );
        // OPTIONAL CUSTOMISATION COMPLETED.

        return chart;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jnessuno;
    private javax.swing.JLabel jnessuno1;
    private javax.swing.JLabel jnessuno2;
    private javax.swing.JLabel jnessuno3;
    private javax.swing.JLabel jnessuno4;
    private javax.swing.JLabel jprima;
    private javax.swing.JLabel jprima1;
    private javax.swing.JLabel jprima2;
    private javax.swing.JLabel jprima3;
    private javax.swing.JLabel jprima4;
    private javax.swing.JLabel jquarta;
    private javax.swing.JLabel jquarta1;
    private javax.swing.JLabel jquarta2;
    private javax.swing.JLabel jquarta3;
    private javax.swing.JLabel jquarta4;
    private javax.swing.JLabel jseconda;
    private javax.swing.JLabel jseconda1;
    private javax.swing.JLabel jseconda2;
    private javax.swing.JLabel jseconda3;
    private javax.swing.JLabel jseconda4;
    private javax.swing.JLabel jterza;
    private javax.swing.JLabel jterza1;
    private javax.swing.JLabel jterza2;
    private javax.swing.JLabel jterza3;
    private javax.swing.JLabel jterza4;
    // End of variables declaration//GEN-END:variables

}
