/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ClientCRC;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author alessandro
 */
public class BarChart2 extends javax.swing.JFrame {

    /**
     * Creates new form BarChart2
     */
    public BarChart2(int uno,int due,int tre,int quattro,int cinque,int sei,
                           int sette,int otto,int nove,int dieci,int undici,int dodici,int tredici,int quattordici,int quindici,int sedici,int diciassette,int diciotto,
                           int diciannove,int venti,int ventuno,int ventidue,int ventitre,int ventiquattro,int venticinque,int pre) {
        initComponents();
        jLabel1.setDisplayedMnemonic(uno);
        jLabel2.setDisplayedMnemonic(due);
        jLabel3.setDisplayedMnemonic(tre);
        jLabel4.setDisplayedMnemonic(quattro);
        jLabel5.setDisplayedMnemonic(cinque);
        jLabel6.setDisplayedMnemonic(sei);
        jLabel7.setDisplayedMnemonic(sette);
        jLabel8.setDisplayedMnemonic(otto);
        jLabel9.setDisplayedMnemonic(nove);
        jLabel10.setDisplayedMnemonic(dieci);
        jLabel11.setDisplayedMnemonic(undici);
        jLabel12.setDisplayedMnemonic(dodici);
        jLabel13.setDisplayedMnemonic(tredici);
        jLabel14.setDisplayedMnemonic(quattordici);
        jLabel15.setDisplayedMnemonic(quindici);
        jLabel16.setDisplayedMnemonic(sedici);
        jLabel17.setDisplayedMnemonic(diciassette);
        jLabel18.setDisplayedMnemonic(diciotto);
        jLabel19.setDisplayedMnemonic(diciannove);
        jLabel20.setDisplayedMnemonic(venti);
        jLabel21.setDisplayedMnemonic(ventuno);
        jLabel22.setDisplayedMnemonic(ventidue);
        jLabel23.setDisplayedMnemonic(ventitre);
        jLabel24.setDisplayedMnemonic(ventiquattro);
        jLabel25.setDisplayedMnemonic(venticinque);
        jLabel26.setDisplayedMnemonic(pre);
        
        final CategoryDataset dataset = createDataset();
        final JFreeChart chart = createChart(dataset);
        final ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(1500, 870));
        setContentPane(chartPanel);
        this.setSize(700, 450);
        this.setLocation(0,320);
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private CategoryDataset createDataset() {

        // row keys...
        final String series1 = "valori MDC";
        //final String series2 = "0-10 giorni in più";
        //final String series3 = "10-20 giorni in più";
        //final String series4 = "20-30 giorni in più";
        //final String series5 = "> 30 giorni in più";

        // column keys...
        final String category1 = "pre";
        final String category2 = "1";
        final String category3 = "2";
        final String category4 = "3";
        final String category5 = "4";
        final String category6 = "5";
        final String category7 = "6";
        final String category8 = "7";
        final String category9 = "8";
        final String category10 = "9";
        final String category11 = "10";
        final String category12 = "11";
        final String category13 = "12";
        final String category14 = "13";
        final String category15 = "14";
        final String category16 = "15";
        final String category17 = "16";
        final String category18 = "17";
        final String category19 = "18";
        final String category20 = "19";
        final String category21 = "20";
        final String category22 = "21";
        final String category23 = "22";
        final String category24 = "23";
        final String category25 = "24";
        final String category26 = "25";

        // create the dataset...
        final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        int pre = jLabel26.getDisplayedMnemonic();
        int uno = jLabel1.getDisplayedMnemonic();
        int due = jLabel2.getDisplayedMnemonic();
        int tre = jLabel3.getDisplayedMnemonic();
        int quattro = jLabel4.getDisplayedMnemonic();
        int cinque = jLabel5.getDisplayedMnemonic();
        int sei = jLabel6.getDisplayedMnemonic();
        int sette = jLabel7.getDisplayedMnemonic();
        int otto = jLabel8.getDisplayedMnemonic();
        int nove = jLabel9.getDisplayedMnemonic();
        int dieci = jLabel10.getDisplayedMnemonic();
        int undici = jLabel11.getDisplayedMnemonic();
        int dodici = jLabel12.getDisplayedMnemonic();
        int tredici = jLabel13.getDisplayedMnemonic();
        int quattordici = jLabel14.getDisplayedMnemonic();
        int quindici = jLabel15.getDisplayedMnemonic();
        int sedici = jLabel16.getDisplayedMnemonic();
        int diciassette = jLabel17.getDisplayedMnemonic();
        int diciotto = jLabel18.getDisplayedMnemonic();
        int diciannove = jLabel19.getDisplayedMnemonic();
        int venti = jLabel20.getDisplayedMnemonic();
        int ventuno = jLabel21.getDisplayedMnemonic();
        int ventidue = jLabel22.getDisplayedMnemonic();
        int ventitre = jLabel23.getDisplayedMnemonic();
        int ventiquattro = jLabel24.getDisplayedMnemonic();
        int venticinque = jLabel25.getDisplayedMnemonic();


        dataset.addValue(pre, series1, category1);
        dataset.addValue(uno, series1, category2);
        dataset.addValue(due, series1, category3);
        dataset.addValue(tre, series1, category4);
        dataset.addValue(quattro, series1, category5);
        dataset.addValue(cinque, series1, category6);
        dataset.addValue(sei, series1, category7);
        dataset.addValue(sette, series1, category8);
        dataset.addValue(otto, series1, category9);
        dataset.addValue(nove, series1, category10);
        dataset.addValue(dieci, series1, category11);
        dataset.addValue(undici, series1, category12);
        dataset.addValue(dodici, series1, category13);
        dataset.addValue(tredici, series1, category14);
        dataset.addValue(quattordici, series1, category15);
        dataset.addValue(quindici, series1, category16);
        dataset.addValue(sedici, series1, category17);
        dataset.addValue(diciassette, series1, category18);
        dataset.addValue(diciotto, series1, category19);
        dataset.addValue(diciannove, series1, category20);
        dataset.addValue(venti, series1, category21);
        dataset.addValue(ventuno, series1, category22);
        dataset.addValue(ventidue, series1, category23);
        dataset.addValue(ventitre, series1, category24);
        dataset.addValue(ventiquattro, series1, category25);
        dataset.addValue(venticinque, series1, category26);

        return dataset;

    }

    /**
     * Creates a sample chart.
     *
     * @param dataset  the dataset.
     *
     * @return The chart.
     */
    private JFreeChart createChart(final CategoryDataset dataset) {

        // create the chart...
        final JFreeChart chart = ChartFactory.createBarChart(
            "Ricoveri con giorni di degenza superiori al valore soglia",         // chart title
            "Valori MDC",               // domain axis label
            "N.ro di ricoveri",                  // range axis label
            dataset,                  // data
            PlotOrientation.VERTICAL, // orientation
            true,                     // include legend
            true,                     // tooltips?
            false                     // URLs?
        );

        // NOW DO SOME OPTIONAL CUSTOMISATION OF THE CHART...

        // set the background color for the chart...
        chart.setBackgroundPaint(Color.gray);

        // get a reference to the plot for further customisation...
        final CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(Color.white);
        plot.setDomainGridlinePaint(Color.black);
        plot.setRangeGridlinePaint(Color.black);

        // set the range axis to display integers only...
        final NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());

        // disable bar outlines...
        final BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setDrawBarOutline(false);

        // set up gradient paints for series...
        final GradientPaint gp0 = new GradientPaint(
            0.0f, 0.0f, Color.green,
            0.0f, 0.0f, Color.black
        );
        final GradientPaint gp1 = new GradientPaint(
            0.0f, 0.0f, Color.yellow,
            0.0f, 0.0f, Color.black
        );
        final GradientPaint gp2 = new GradientPaint(
            0.0f, 0.0f, Color.cyan,
            0.0f, 0.0f, Color.black
        );
        final GradientPaint gp3 = new GradientPaint(
            0.0f, 0.0f, Color.magenta,
            0.0f, 0.0f, Color.black
        );
        final GradientPaint gp4 = new GradientPaint(
            0.0f, 0.0f, Color.red,
            0.0f, 0.0f, Color.black
        );
        renderer.setSeriesPaint(0, gp0);
        renderer.setSeriesPaint(1, gp1);
        renderer.setSeriesPaint(2, gp2);
        renderer.setSeriesPaint(3, gp3);
        renderer.setSeriesPaint(4, gp4);

        final CategoryAxis domainAxis = plot.getDomainAxis();
        domainAxis.setCategoryLabelPositions(
            CategoryLabelPositions.createUpRotationLabelPositions(Math.PI / 6.0)
        );
        // OPTIONAL CUSTOMISATION COMPLETED.

        return chart;

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        jLabel15.setText("jLabel15");

        jLabel16.setText("jLabel16");

        jLabel17.setText("jLabel17");

        jLabel18.setText("jLabel18");

        jLabel19.setText("jLabel19");

        jLabel20.setText("jLabel20");

        jLabel21.setText("jLabel21");

        jLabel22.setText("jLabel22");

        jLabel23.setText("jLabel23");

        jLabel24.setText("jLabel24");

        jLabel25.setText("jLabel25");

        jLabel26.setText("jLabel26");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel26))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
