/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CinqueClassi.java
 *
 * Created on 13-feb-2012, 15.22.55
 */

package ClientCRC;
import java.awt.Font;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author alessandro
 */
public class CinqueClassi extends javax.swing.JFrame {

    /** Creates new form CinqueClassi */
    public CinqueClassi(int zero, int uno, int due, int tre, int quattro) {
        initComponents();
        jprima.setDisplayedMnemonic(zero);
        jseconda.setDisplayedMnemonic(uno);
        jterza.setDisplayedMnemonic(due);
        jquarta.setDisplayedMnemonic(tre);
        jquinta.setDisplayedMnemonic(quattro);
        setContentPane(createDemoPanel());
        this.setLocation(470,0);
        this.setDefaultCloseOperation(DueClassi.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jprima = new javax.swing.JLabel();
        jseconda = new javax.swing.JLabel();
        jterza = new javax.swing.JLabel();
        jquarta = new javax.swing.JLabel();
        jquinta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jprima.setText("jLabel1");

        jseconda.setText("jLabel1");

        jterza.setText("jLabel1");

        jquarta.setText("jLabel1");

        jquinta.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jprima)
                    .addComponent(jseconda)
                    .addComponent(jterza)
                    .addComponent(jquarta)
                    .addComponent(jquinta))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jprima)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jseconda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jterza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jquarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jquinta)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private PieDataset createDataset() {

        int prima = jprima.getDisplayedMnemonic();
        int seconda = jseconda.getDisplayedMnemonic();
        int terza =jterza.getDisplayedMnemonic();
        int quarta = jquarta.getDisplayedMnemonic();
        int quinta = jquinta.getDisplayedMnemonic();


        int tot = prima + seconda + terza + quarta + quinta;
        float primaperc = ((100 * prima)/tot);
        float secondaperc =((100 * seconda)/ tot);
        float terzaperc =((100 * terza)/tot);
        float quartaperc = ((100 * quarta)/tot);
        float quintaperc = ((100 * quinta)/tot);



        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("classe 0", new Double(primaperc));
        dataset.setValue("classe 1", new Double(secondaperc));
        dataset.setValue("classe 2",new Double(terzaperc));
        dataset.setValue("classe 3",new Double(quartaperc));
        dataset.setValue("classe 4",new Double(quintaperc));

        return dataset;
    }


    private static JFreeChart createChart(PieDataset dataset) {

        JFreeChart chart = ChartFactory.createPieChart(
            "popolazione statistica divisa per DRG in cinque classi",  // chart title
            dataset,             // data
            true,               // include legend
            true,
            false
        );
        PiePlot plot = (PiePlot) chart.getPlot();
        plot.setLabelFont(new Font("Verdana", Font.PLAIN, 12));
        plot.setNoDataMessage("No data available");
        plot.setCircular(false);
        plot.setLabelGap(0.02);
        return chart;

    }

     public  JPanel createDemoPanel() {
        JFreeChart chart = createChart(createDataset());
        return new ChartPanel(chart);
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jprima;
    private javax.swing.JLabel jquarta;
    private javax.swing.JLabel jquinta;
    private javax.swing.JLabel jseconda;
    private javax.swing.JLabel jterza;
    // End of variables declaration//GEN-END:variables

}
