/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EtàPie.java
 *
 * Created on 8-feb-2012, 13.56.30
 */

package ClientCRC;

import java.awt.Font;

import javax.swing.JPanel;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author alessandro
 */
public class EtàPie extends javax.swing.JFrame {

    /** Creates new form EtàPie */
    public EtàPie(int prima, int seconda, int terza, int quarta, int quinta, int sesta, int settima, int ottava, int nona, int decima) {
        initComponents();
        
        System.out.println(prima);
        jprima.setDisplayedMnemonic(prima);
        jseconda.setDisplayedMnemonic(seconda);
        jterza.setDisplayedMnemonic(terza);
        jquarta.setDisplayedMnemonic(quarta);
        jquinta.setDisplayedMnemonic(quinta);
        jsesta.setDisplayedMnemonic(sesta);
        jsettima.setDisplayedMnemonic(settima);
        jottava.setDisplayedMnemonic(ottava);
        jnona.setDisplayedMnemonic(nona);
        jdecima.setDisplayedMnemonic(decima);
        setContentPane(createDemoPanel());
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jprima = new javax.swing.JLabel();
        jseconda = new javax.swing.JLabel();
        jterza = new javax.swing.JLabel();
        jquarta = new javax.swing.JLabel();
        jquinta = new javax.swing.JLabel();
        jsesta = new javax.swing.JLabel();
        jsettima = new javax.swing.JLabel();
        jottava = new javax.swing.JLabel();
        jnona = new javax.swing.JLabel();
        jdecima = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jprima.setText("jLabel1");

        jseconda.setText("jLabel1");

        jterza.setText("jLabel1");

        jquarta.setText("jLabel1");

        jquinta.setText("jLabel1");

        jsesta.setText("jLabel1");

        jsettima.setText("jLabel1");

        jottava.setText("jLabel1");

        jnona.setText("jLabel1");

        jdecima.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jprima)
                        .addGap(18, 18, 18)
                        .addComponent(jseconda)
                        .addGap(18, 18, 18)
                        .addComponent(jterza)
                        .addGap(18, 18, 18)
                        .addComponent(jquarta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jquinta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsesta)
                        .addGap(18, 18, 18)
                        .addComponent(jsettima))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jottava)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jnona)
                        .addGap(18, 18, 18)
                        .addComponent(jdecima)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jprima)
                    .addComponent(jseconda)
                    .addComponent(jterza)
                    .addComponent(jquarta)
                    .addComponent(jquinta)
                    .addComponent(jsesta)
                    .addComponent(jsettima))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jottava)
                    .addComponent(jnona)
                    .addComponent(jdecima))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private PieDataset createDataset() {
        
        int prima = jprima.getDisplayedMnemonic();
        
        int seconda = jseconda.getDisplayedMnemonic();
        
        int terza = jterza.getDisplayedMnemonic();
        int quarta = jquarta.getDisplayedMnemonic();
        int quinta = jquinta.getDisplayedMnemonic();
        int sesta = jsesta.getDisplayedMnemonic();
        int settima = jsettima.getDisplayedMnemonic();
        int ottava = jottava.getDisplayedMnemonic();
        int nona = jnona.getDisplayedMnemonic();
        int decima = jdecima.getDisplayedMnemonic();
        
        int tot = prima + seconda + terza + quarta + quinta +sesta + settima + ottava + nona + decima;
        
        float primaperc = ((100 * prima)/tot);
        float secondaperc =((100 * seconda)/ tot);
        float terzaperc = ((100 * terza)/ tot);
        float quartaperc = ((100 * quarta)/ tot);
        float quintaperc = ((100 * quinta)/ tot);
        float sestaperc = ((100 * sesta)/ tot);
        float settimaperc = ((100 * settima)/ tot);
        float ottavaperc = ((100 * ottava)/ tot);
        float nonaperc = ((100 * nona)/ tot);
        float decimaperc = ((100 * decima)/ tot);


        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("0-10 anni", new Double(primaperc));
        dataset.setValue("10-20 anni", new Double(secondaperc));
        dataset.setValue("20-30 anni", new Double(terzaperc));
        dataset.setValue("30-40 anni", new Double(quartaperc));
        dataset.setValue("40-50 anni", new Double(quintaperc));
        dataset.setValue("50-60 anni", new Double(sestaperc));
        dataset.setValue("60-70 anni", new Double(settimaperc));
        dataset.setValue("70-80 anni", new Double(ottavaperc));
        dataset.setValue("80-90 anni", new Double(nonaperc));
        dataset.setValue("> 90 anni", new Double(decimaperc));

        return dataset;
    }

    private static JFreeChart createChart(PieDataset dataset) {

        JFreeChart chart = ChartFactory.createPieChart(
            "popolazione statistica divisa per età",  // chart title
            dataset,             // data
            true,               // include legend
            true,
            false
        );

        PiePlot plot = (PiePlot) chart.getPlot();
        plot.setLabelFont(new Font("SansSerif", Font.PLAIN, 12));
        plot.setNoDataMessage("No data available");
        plot.setCircular(false);
        plot.setLabelGap(0.02);
        return chart;

    }

     public  JPanel createDemoPanel() {
        JFreeChart chart = createChart(createDataset());
        return new ChartPanel(chart);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jdecima;
    private javax.swing.JLabel jnona;
    private javax.swing.JLabel jottava;
    private javax.swing.JLabel jprima;
    private javax.swing.JLabel jquarta;
    private javax.swing.JLabel jquinta;
    private javax.swing.JLabel jseconda;
    private javax.swing.JLabel jsesta;
    private javax.swing.JLabel jsettima;
    private javax.swing.JLabel jterza;
    // End of variables declaration//GEN-END:variables

}
