/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ClientCRC;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author alessandro
 */
public class GiorniRic extends javax.swing.JFrame {

    /**
     * Creates new form GiorniRic
     */
    public GiorniRic(int nessuno18, int prima18, int seconda18, int terza18, int quarta18, int nessuno40, int prima40, int seconda40,
                     int terza40, int quarta40,int nessuno60,int prima60,int seconda60,int terza60,int quarta60,int nessuno80,int  prima80,
                     int seconda80,int terza80,int quarta80,int nessunomagg,int primamagg,int secondamagg,int terzamagg,int quartamagg,
                     int dentro, int fuori,int uno,int due,int tre,int quattro,int cinque,int sei,
                           int sette,int otto,int nove,int dieci,int undici,int dodici,int tredici,int quattordici,int quindici,int sedici,int diciassette,int diciotto,
                           int diciannove,int venti,int ventuno,int ventidue,int ventitre,int ventiquattro,int venticinque,int pre) {
        initComponents();
        this.getContentPane().setBackground(Color.DARK_GRAY);
        this.setIconImage(new ImageIcon("C:\\SOAP\\images\\icon.gif").getImage());
        jNessuno18.setDisplayedMnemonic(nessuno18);
        jPrima18.setDisplayedMnemonic(prima18);
        jSeconda18.setDisplayedMnemonic(seconda18);
        jTerza18.setDisplayedMnemonic(terza18);
        jQuarta18.setDisplayedMnemonic(quarta18);
        jNessuno40.setDisplayedMnemonic(nessuno40);
        jPrima40.setDisplayedMnemonic(prima40);
        jSeconda40.setDisplayedMnemonic(seconda40);
        jTerza40.setDisplayedMnemonic(terza40);
        jQuarta40.setDisplayedMnemonic(quarta40);
        jNessuno60.setDisplayedMnemonic(nessuno60);
        jPrima60.setDisplayedMnemonic(prima60);
        jSeconda60.setDisplayedMnemonic(seconda60);
        jTerza60.setDisplayedMnemonic(terza60);
        jQuarta60.setDisplayedMnemonic(quarta60);
        jNessuno80.setDisplayedMnemonic(nessuno80);
        jPrima80.setDisplayedMnemonic(prima80);
        jSeconda80.setDisplayedMnemonic(seconda80);
        jTerza80.setDisplayedMnemonic(terza80);
        jQuarta80.setDisplayedMnemonic(quarta80);
        jNessunoMagg.setDisplayedMnemonic(nessunomagg);
        jPrimaMagg.setDisplayedMnemonic(primamagg);
        jSecondaMagg.setDisplayedMnemonic(secondamagg);
        jTerzaMagg.setDisplayedMnemonic(terzamagg);
        jQuartaMagg.setDisplayedMnemonic(quartamagg);
        String f = String.valueOf(fuori);
        jFuori.setText(f);
        int somma = (fuori + dentro);
        String tutto = String.valueOf(somma);
        jTutto.setText(tutto);
        jDentro.setDisplayedMnemonic(dentro);
        jLabel6.setDisplayedMnemonic(uno);
        jLabel7.setDisplayedMnemonic(due);
        jLabel8.setDisplayedMnemonic(tre);
        jLabel9.setDisplayedMnemonic(quattro);
        jLabel10.setDisplayedMnemonic(cinque);
        jLabel11.setDisplayedMnemonic(sei);
        jLabel12.setDisplayedMnemonic(sette);
        jLabel13.setDisplayedMnemonic(otto);
        jLabel14.setDisplayedMnemonic(nove);
        jLabel15.setDisplayedMnemonic(dieci);
        jLabel16.setDisplayedMnemonic(undici);
        jLabel17.setDisplayedMnemonic(dodici);
        jLabel18.setDisplayedMnemonic(tredici);
        jLabel19.setDisplayedMnemonic(quattordici);
        jLabel20.setDisplayedMnemonic(quindici);
        jLabel21.setDisplayedMnemonic(sedici);
        jLabel22.setDisplayedMnemonic(diciassette);
        jLabel23.setDisplayedMnemonic(diciotto);
        jLabel24.setDisplayedMnemonic(diciannove);
        jLabel25.setDisplayedMnemonic(venti);
        jLabel26.setDisplayedMnemonic(ventuno);
        jLabel27.setDisplayedMnemonic(ventidue);
        jLabel28.setDisplayedMnemonic(ventitre);
        jLabel29.setDisplayedMnemonic(ventiquattro);
        jLabel30.setDisplayedMnemonic(venticinque);
        jLabel31.setDisplayedMnemonic(pre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jNessuno18 = new javax.swing.JLabel();
        jPrima18 = new javax.swing.JLabel();
        jSeconda18 = new javax.swing.JLabel();
        jTerza18 = new javax.swing.JLabel();
        jQuarta18 = new javax.swing.JLabel();
        jPrima40 = new javax.swing.JLabel();
        jNessuno40 = new javax.swing.JLabel();
        jSeconda40 = new javax.swing.JLabel();
        jTerza40 = new javax.swing.JLabel();
        jQuarta40 = new javax.swing.JLabel();
        jNessuno60 = new javax.swing.JLabel();
        jPrima60 = new javax.swing.JLabel();
        jSeconda60 = new javax.swing.JLabel();
        jTerza60 = new javax.swing.JLabel();
        jQuarta60 = new javax.swing.JLabel();
        jNessuno80 = new javax.swing.JLabel();
        jPrima80 = new javax.swing.JLabel();
        jSeconda80 = new javax.swing.JLabel();
        jTerza80 = new javax.swing.JLabel();
        jQuarta80 = new javax.swing.JLabel();
        jNessunoMagg = new javax.swing.JLabel();
        jPrimaMagg = new javax.swing.JLabel();
        jSecondaMagg = new javax.swing.JLabel();
        jTerzaMagg = new javax.swing.JLabel();
        jQuartaMagg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jFuori = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTutto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDentro = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("ricoveri con giorni di degenza superiori al valore soglia divisi per età");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 0));
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("ricoveri con giorni di degenza superiori al valore soglia divisi per MDC");

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 0));
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("ricoveri con giorni di degenza superiori al valore soglia : (");

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 0));
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jFuori.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jFuori.setForeground(new java.awt.Color(255, 255, 0));
        jFuori.setText("jLabel4");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText(") su (");

        jTutto.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTutto.setForeground(new java.awt.Color(255, 255, 0));
        jTutto.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText(")");

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenuBar1.setForeground(new java.awt.Color(102, 102, 102));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFuori)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTutto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jNessuno18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeconda18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jQuarta18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jNessuno40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTerza40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jNessuno60)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeconda60)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jQuarta60))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPrima18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTerza18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPrima40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeconda40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jQuarta40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPrima60)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTerza60)))
                                .addGap(18, 18, 18)
                                .addComponent(jNessuno80)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPrima80)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeconda80)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTerza80)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jQuarta80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jNessunoMagg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPrimaMagg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSecondaMagg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTerzaMagg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jQuartaMagg))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(185, 185, 185)
                                        .addComponent(jDentro))))
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addGap(48, 48, 48)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jNessuno18)
                                    .addComponent(jSeconda18)
                                    .addComponent(jQuarta18)
                                    .addComponent(jNessuno40)
                                    .addComponent(jTerza40)
                                    .addComponent(jNessuno60)
                                    .addComponent(jSeconda60)
                                    .addComponent(jQuarta60))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPrima18)
                                    .addComponent(jTerza18)
                                    .addComponent(jPrima40)
                                    .addComponent(jSeconda40)
                                    .addComponent(jQuarta40)
                                    .addComponent(jPrima60)
                                    .addComponent(jTerza60)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jNessuno80)
                                .addComponent(jPrima80)
                                .addComponent(jSeconda80)
                                .addComponent(jTerza80)
                                .addComponent(jQuarta80))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNessunoMagg)
                            .addComponent(jPrimaMagg)
                            .addComponent(jSecondaMagg)
                            .addComponent(jTerzaMagg)
                            .addComponent(jQuartaMagg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDentro)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFuori)
                    .addComponent(jLabel4)
                    .addComponent(jTutto)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27)
                        .addComponent(jLabel28)
                        .addComponent(jLabel29)
                        .addComponent(jLabel30)
                        .addComponent(jLabel31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int nessuno18 = jNessuno18.getDisplayedMnemonic();
        int prima18 = jPrima18.getDisplayedMnemonic();
        int seconda18 = jSeconda18.getDisplayedMnemonic();
        int terza18 = jTerza18.getDisplayedMnemonic();
        int quarta18 = jQuarta18.getDisplayedMnemonic();
        int nessuno40 = jNessuno40.getDisplayedMnemonic();
        int prima40 = jPrima40.getDisplayedMnemonic();
        int seconda40 = jSeconda40.getDisplayedMnemonic();
        int terza40 = jTerza40.getDisplayedMnemonic();
        int quarta40 = jQuarta40.getDisplayedMnemonic();
        int nessuno60 = jNessuno60.getDisplayedMnemonic();
        int prima60 = jPrima60.getDisplayedMnemonic();
        int seconda60 = jSeconda60.getDisplayedMnemonic();
        int terza60 = jTerza60.getDisplayedMnemonic();
        int quarta60 = jQuarta60.getDisplayedMnemonic();
        int nessuno80 = jNessuno80.getDisplayedMnemonic();
        int prima80 = jPrima80.getDisplayedMnemonic();
        int seconda80 = jSeconda80.getDisplayedMnemonic();
        int terza80 = jTerza80.getDisplayedMnemonic();
        int quarta80 = jQuarta80.getDisplayedMnemonic();
        int nessunomagg = jNessunoMagg.getDisplayedMnemonic();
        int primamagg = jPrimaMagg.getDisplayedMnemonic();
        int secondamagg = jSecondaMagg.getDisplayedMnemonic();
        int terzamagg = jTerzaMagg.getDisplayedMnemonic();
        int quartamagg = jQuartaMagg.getDisplayedMnemonic();
        
        new BarChartDemo(nessuno18, prima18, seconda18, terza18, quarta18, nessuno40, prima40, seconda40, terza40, quarta40,
                          nessuno60, prima60, seconda60, terza60, quarta60,nessuno80, prima80, seconda80, terza80, quarta80,
                          nessunomagg, primamagg, secondamagg, terzamagg, quartamagg).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int dentro = jDentro.getDisplayedMnemonic();
        int fuori = Integer.valueOf(jFuori.getText());
        new DentroFuori(fuori, dentro).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int uno = jLabel6.getDisplayedMnemonic();
       int due = jLabel7.getDisplayedMnemonic();
       int tre = jLabel8.getDisplayedMnemonic();
       int quattro = jLabel9.getDisplayedMnemonic();
       int cinque = jLabel10.getDisplayedMnemonic();
       int sei = jLabel11.getDisplayedMnemonic();
       int sette = jLabel12.getDisplayedMnemonic();
       int otto = jLabel13.getDisplayedMnemonic();
       int nove = jLabel14.getDisplayedMnemonic();
       int dieci = jLabel15.getDisplayedMnemonic();
       int undici = jLabel16.getDisplayedMnemonic();
       int dodici = jLabel17.getDisplayedMnemonic();
       int tredici = jLabel18.getDisplayedMnemonic();
       int quattordici = jLabel19.getDisplayedMnemonic();
       int quindici = jLabel20.getDisplayedMnemonic();
       int sedici = jLabel21.getDisplayedMnemonic();
       int diciassette = jLabel22.getDisplayedMnemonic();
       int diciotto = jLabel23.getDisplayedMnemonic();
       int diciannove = jLabel24.getDisplayedMnemonic();
       int venti = jLabel25.getDisplayedMnemonic();
       int ventuno = jLabel26.getDisplayedMnemonic();
       int ventidue = jLabel27.getDisplayedMnemonic();
       int ventitre = jLabel28.getDisplayedMnemonic();
       int ventiquattro = jLabel29.getDisplayedMnemonic();
       int venticinque = jLabel30.getDisplayedMnemonic();
       int pre = jLabel31.getDisplayedMnemonic();
       
       new BarChart2(uno, due, tre, quattro, cinque, sei, sette, otto, nove , dieci, undici , dodici, tredici, quattordici,
                     quindici, sedici, diciassette, diciotto, diciannove, venti, ventuno, ventidue, ventitre, ventiquattro,
                     venticinque, pre).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jDentro;
    private javax.swing.JLabel jFuori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jNessuno18;
    private javax.swing.JLabel jNessuno40;
    private javax.swing.JLabel jNessuno60;
    private javax.swing.JLabel jNessuno80;
    private javax.swing.JLabel jNessunoMagg;
    private javax.swing.JLabel jPrima18;
    private javax.swing.JLabel jPrima40;
    private javax.swing.JLabel jPrima60;
    private javax.swing.JLabel jPrima80;
    private javax.swing.JLabel jPrimaMagg;
    private javax.swing.JLabel jQuarta18;
    private javax.swing.JLabel jQuarta40;
    private javax.swing.JLabel jQuarta60;
    private javax.swing.JLabel jQuarta80;
    private javax.swing.JLabel jQuartaMagg;
    private javax.swing.JLabel jSeconda18;
    private javax.swing.JLabel jSeconda40;
    private javax.swing.JLabel jSeconda60;
    private javax.swing.JLabel jSeconda80;
    private javax.swing.JLabel jSecondaMagg;
    private javax.swing.JLabel jTerza18;
    private javax.swing.JLabel jTerza40;
    private javax.swing.JLabel jTerza60;
    private javax.swing.JLabel jTerza80;
    private javax.swing.JLabel jTerzaMagg;
    private javax.swing.JLabel jTutto;
    // End of variables declaration//GEN-END:variables
}
