/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ClientCRC;
import java.awt.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Set;
import javax.swing.ImageIcon;
/**
 *
 * @author alessandro
 */
public class Progress2 extends javax.swing.JFrame {
    Frame B = this;
    /**
     * Creates new form Progress2
     */private Font myFont = new Font("Tahoma", Font.PLAIN,11);
    
    public Progress2(Frame A) {
        initComponents();
        A.setAlwaysOnTop(true);
        this.setAlwaysOnTop(true);
        this.getContentPane().setBackground(Color.DARK_GRAY);
        this.setIconImage(new ImageIcon("C:\\SOAP\\images\\icon.gif").getImage());
        
        // Prendo le dimensioni del desktop
        Dimension dim_schermo = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcolo la posizione orizzontale della finestra
        int posX = (int) (dim_schermo.width - getWidth())/2;

        // Calcolo la posizione verticale della finestra
        int posY = (int) (dim_schermo.height - getHeight())/2;

        // Posiziono la finestra
        setLocation(posX, posY);
        this.getContentPane().setBackground(Color.DARK_GRAY);
        this.setIconImage(new ImageIcon("C:\\SOAP\\images\\icon.gif").getImage());
        this.setFont(myFont);
        
        jProgressBar1.setStringPainted(true);
        jProgressBar1.setIndeterminate(true);
        

        MyThread t = new MyThread();
        t.start();


        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    class MyThread extends Thread { 
        
        public void run(){
            
            


   
            boolean exists = (new File("c:\\SOAP\\SPSSOUTPUT.htm")).exists();
        while (! exists){
            
            System.out.println(exists);
            exists = (new File("c:\\SOAP\\SPSSOUTPUT.htm")).exists();
        }
        new VuoiSalvare().setVisible(true);
        B.dispose();
        
        }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 204));
        jProgressBar1.setForeground(new java.awt.Color(102, 255, 0));
        jProgressBar1.setString("");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Caricamento in corso...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
